[package]
name = "voxels"
version = "0.1.0"
edition = "2021"
default-run = "voxels"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
smooth-bevy-cameras = "0.2"
bevy-inspector-egui = "0.8"
bevy_egui = "0.11"
