[package]
name = "voxels"
version = "0.1.0"
publish = false
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
winit = "0.24"
wgpu = "0.8"
tracing = "0.1"
tracing-subscriber = "0.2"
futures-lite = "1.11"
bytemuck = { version = "1.5", features = ["derive"] }
glam = "0.14"
simdnoise = "3"
rayon = "1.5"
egui = "0.12"
epi = "0.12"
egui_wgpu_backend = "0.8"
egui_winit_platform = "0.7"
