[package]
name = "voxels"
version = "0.1.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24"
wgpu = "0.8"
tracing = "0.1"
tracing-subscriber = "0.2"
futures = "0.3"
shaderc = "0.7"
bytemuck = { version = "1.5", features = ["derive"] }
